name: AWS ECR Security Report
branding:
  icon: alert-octagon
  color: gray-dark
description: Retrieve scan results for a Docker image stored in AWS ECR and fail if vulnerabilities are found.
inputs:
  repository:
    description: ECR repository, eg myorg/myimage.
    required: true
  tag:
    description: Image tag to scan.
    required: true
  fail_threshold:
    description: >
      Fail if any vulnerabilities equal to or above this severity level are detected.
      Valid values: critical, high, medium, low, informational undefined, none.
    default: critical
  region:
    description: AWS region where the ECR repository is located.
    default: us-east-2
  ignore_list:
    description: List of CVE IDs to ignore in the vulnerability findings.
    default: ""
  pr_comment:
    description: Whether to post a comment on the PR with the scan results.
    default: true
outputs:
  critical:
    description: Number of critical vulnerabilities detected.
  high:
    description: Number of high vulnerabilities detected.
  medium:
    description: Number of medium vulnerabilities detected.
  low:
    description: Number of low vulnerabilities detected.
  informational:
    description: Number of informational vulnerabilities detected.
  undefined:
    description: Number of undefined severity vulnerabilities detected.
  total:
    description: Total number of vulnerabilities detected.
  detailed_findings:
    description: Detailed findings of the scan.

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@v1
    - name: Install dependencies with uv
      shell: bash
      run: |
        uv pip install --system ${{ github.action_path }}
    - name: Pull Scan Results
      id: scan
      continue-on-error: true
      shell: bash
      run: |
        ecr-scan '${{ inputs.repository }}' \
                 '${{ inputs.tag }}' \
                 --fail_threshold='${{ inputs.fail_threshold }}' \
                 --ignore-list='${{ inputs.ignore_list }}'
    - name: PR Feedback Comment
      if: |
        inputs.pr_comment &&
        steps.scan.outputs.total != '0' &&
        github.event_name == 'pull_request' &&
        (success() || failure())
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## 🛡️ AWS ECR Security Scan Results
          ### 📦 Image: ${{ inputs.repository }}:${{ inputs.tag }}
          ### 📈 Vulnerability Summary
          ${{ steps.scan.outputs.critical != '0' && format('⚠️ CRITICAL: {0}', steps.scan.outputs.critical) || '' }}
          ${{ steps.scan.outputs.high != '0' && format('🔴 HIGH: {0}', steps.scan.outputs.high) || '' }}
          ${{ steps.scan.outputs.medium != '0' && format('🟡 MEDIUM: {0}', steps.scan.outputs.medium) || '' }}
          ${{ steps.scan.outputs.low != '0' && format('🟢 LOW: {0}', steps.scan.outputs.low) || '' }}
          ${{ steps.scan.outputs.informational != '0' && format('🔵 INFORMATIONAL: {0}', steps.scan.outputs.informational) || '' }}
          ${{ steps.scan.outputs.undefined != '0' && format('🟣 UNDEFINED: {0}', steps.scan.outputs.undefined) || '' }}

          ### 🔍 Detailed Findings
          ```json
          ${{ steps.scan.outputs.detailed_findings }}
          ```
          ${{ (steps.scan.outputs.critical != '0' || steps.scan.outputs.high != '0') && '⚠️ **Build Failed**: Critical or high severity vulnerabilities were detected. These must be addressed before merging.' || 'Please review these security findings before merging.' }}
    - name: Fail if scan failed
      if: steps.scan.outcome == 'failure'
      shell: bash
      run: exit 1
